---

- name: install apache
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - httpd-devel
  become: yes
  become_user: root

- name: create apache web service configuration directory
  file: "path={{ item }} state=directory mode=0775 owner={{ apache_user }} recurse=yes"
  with_items:
    - "{{ apache_sites_available_dir }}"
  become: yes
  become_user: root

# create enabled sites directory that links to available sites directory
- name: setup nginx sites-available symlink
  file: "path={{ apache_sites_enabled_dir }}  src={{ apache_sites_available_dir }} state=link force=yes mode=0775 owner={{ apache_user }}"
  become: yes
  become_user: root

- name: enable apache to start on boot (RHEL/CentOS 7)
  systemd:
    state: started
    enabled: yes
    name: httpd
  become: yes
  become_user: root


- name: tell apache to use sites-enabled directory
  lineinfile:
    dest: "/etc/httpd/conf/httpd.conf"
    line: "IncludeOptional sites-enabled/*.conf"
  become: yes
  become_user: root
  notify:
  - restart apache