---

- hosts: all
  roles:
  - role: common

- hosts: task_broker
  roles:
  - role: task_broker

- hosts: elasticsearch
  roles:
  - role: elasticsearch

- hosts: kibana
  roles:
  - role: kibana

- hosts: task_db
  roles:
  - role: task_db

- hosts: dfs_server
  roles:
  - role: dfs_server

- hosts: ms_worker
  roles:
  - role: dfs_client
  - role: python3
  - role: ms_worker


- hosts: webserver
  roles:
  - role: dfs_client
  - role: python3
  - role: webserver



