---
- name: install Java
  yum:
    name: java
    state: present
  become: yes
  become_user: root

- include: ../../elasticsearch/tasks/import_elastic_gpg_key.yml
- include: setup_kibana.yml
- include: setup_firewall_rules.yml
