---

- name: install mod_wsgi
  pip:
    name: mod_wsgi
    state: latest
    virtualenv: "{{ mod_wsgi_venv }}"
  become: yes
  become_user: "{{ mod_wsgi_user }}"

- name: load mod_wsgi module
  command: "{{ mod_wsgi_venv }}/bin/mod_wsgi-express install-module"
  become: yes
  become_user: root

- name: create run directory for mod_wsgi
  file: "path=/var/run/wsgi state=directory mode=0775 owner={{ ms_user }} group=root recurse=yes"
  become: yes
  become_user: root

- name: use mod_wsgi run directory
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: 'WSGISocketPrefix /var/run/wsgi'
  become: yes
  become_user: root
  notify:
  - restart apache
