---

- name: install epel-release repo
  yum:
    name: epel-release
    state: present
  become: yes
  become_user: root

- name: install multiscanner system dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - automake
    - curl
    - gcc
    - libffi-devel
    - libtool
    - make
    - python-devel
    - python-pip
    - ssdeep-devel
    - tar
    - git
  become: yes
  become_user: root

- name: copy multiscanner source
  copy:
    src: "../../{{local_resource_prefix}}/multiscanner.tgz"
    dest: "{{ multiscanner_install_prefix }}"
  become: yes
  become_user: root

- name: unzip multiscanner source
  unarchive:
    src: "{{ multiscanner_install_prefix }}/multiscanner.tgz"
    dest: "{{ multiscanner_install_prefix }}"
    remote_src: yes
    creates: "{{ multiscanner_install_prefix }}/multiscanner"
    owner: "{{ ms_user }}"
    group: root
  become: yes
  become_user: root

- name: create multiscanner virtualenv directory and set permissions
  file: "path={{ multiscanner_venv }} state=directory mode=0700 owner={{ ms_user }} recurse=yes"
  become: yes
  become_user: root

- name: install multiscanner python dependencies
  pip:
    requirements: "{{ multiscanner_install_prefix }}/multiscanner/requirements3.txt"
    virtualenv: "{{ multiscanner_venv }}"
    virtualenv_python: "{{ python_install_prefix }}/bin/python"
    virtualenv_site_packages: yes
  become: yes
  become_user: "{{ ms_user }}"

# Copy configs
- name: copy multiscanner main config
  template: src=config.ini.j2 dest={{ multiscanner_install_prefix }}/config.ini mode=755 owner=multiscanner group=root
  register: restart_ms_celery
  become: yes
  become_user: root


- name: copy multiscanner api config
  template: src=api_config.ini.j2 dest={{ multiscanner_install_prefix }}/api_config.ini mode=755 owner=multiscanner group=root
  register: restart_ms_celery
  become: yes
  become_user: root


- name: copy multiscanner storage config
  template: src=storage.ini.j2 dest={{ multiscanner_install_prefix }}/storage.ini mode=755 owner=multiscanner group=root
  register: restart_ms_celery
  become: yes
  become_user: root


# Service setup
- name: copy multiscanner systemd config
  template: src=mscan-worker.service.j2 dest=/etc/systemd/system/mscan-worker.service mode=755 owner=multiscanner group=root
  register: restart_ms_celery
  become: yes
  become_user: root

- name: enable multiscanner worker to start on boot (RHEL/CentOS 7)
  systemd:
    state: started
    enabled: yes
    name: mscan-worker
  become: yes
  become_user: root

# We don't want this to be called before we set up the systemd file.
# However, we don't want the systemd setup to happen until the config files
# have been copied, or MS won't start. Hence this awkward placement...
- name: restart multiscanner-celery if any configs changed
  systemd: state=restarted name=mscan-worker
  when: restart_ms_celery | changed
  become: yes
  become_user: root

