---

# Service setup
- name: copy multiscanner systemd config
  template: src=mscan-worker.service.j2 dest=/etc/systemd/system/mscan-worker.service mode=755 owner=multiscanner group=root
  become: yes
  become_user: root
  notify:
    - reload systemd
    - restart multiscanner-celery

- name: enable multiscanner worker to start on boot (RHEL/CentOS 7)
  systemd:
    state: started
    enabled: yes
    name: mscan-worker
  become: yes
  become_user: root


