---

- name: add firewall exceptions for elasticsearch
  firewalld: port={{ item }} permanent=true zone={{ elasticsearch_firewall_zone }} state=enabled immediate=true
  with_items: "{{ elasticsearch_ports }}"
  become: yes
  become_user: root
